  
---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
    
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

-name: "create backend folder"
  file:
    path: /home/ubuntu/backend
    state: directory

-name: "copy backend folder"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu
    
- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls
 
 
